(()=>{
'use strict';
const H='qrStudioHistoryV1',T='qrStudioTheme',MAX=100,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const S={type:'url',payload:'',svg:'',scanner:null,running:false,logo:null,batch:[],cancelBatch:false};
const friendly=e=>/too large/i.test(e.message)?'Content is too long for one QR code at this error-correction level. Shorten it, or choose a lower level (L holds the most).':e.message;
const vesc=s=>String(s).replace(/\\/g,'\\\\').replace(/;/g,'\\;').replace(/,/g,'\\,').replace(/\r?\n/g,'\\n');
const vunesc=s=>String(s).replace(/\\([\\;,nN])/g,(_,c)=>/[nN]/.test(c)?'\n':c);
const ecl=()=>S.logo?'H':(($('#ecLevel')&&$('#ecLevel').value)||'H');
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const v=id=>$('#'+id)?.value.trim()||'';
const templates=[
 ['Website','url','A clean website QR starter.','https://example.com'],['Wi-Fi','wifi','Share a network without typing credentials.','My Wi-Fi'],['Contact','contact','Share a vCard contact.','Your name'],['Email','email','Pre-fill an email message.','name@example.com'],['SMS','sms','Open a pre-filled text message.','+123456789'],['Event','event','Share an event or appointment.','My Event'],['Social','social','Link to a social profile.','https://instagram.com/'],['WhatsApp','whatsapp','Open a WhatsApp chat.','+93700000000'],['App link','app','Share an app or download URL.','https://example.com/app']
];
const typeLabels={url:'URL',text:'Text',wifi:'Wi-Fi',email:'Email',phone:'Phone',contact:'Contact',location:'Location',sms:'SMS',event:'Event',social:'Social',whatsapp:'WhatsApp',app:'App link'};
function renderFields(){
 const m={
 url:`<div class="field"><label>Website URL<input id="url" type="url" placeholder="https://example.com"></label></div>`,
 text:`<div class="field"><label>Text<textarea id="text" placeholder="Enter any text"></textarea></label></div>`,
 wifi:`<div class="field"><label>Network name / SSID<input id="ssid" placeholder="My Wi-Fi"></label></div><div class="field"><label>Password<input id="password" type="password"></label></div><div class="field"><label>Security<select id="security"><option value="WPA">WPA/WPA2</option><option value="WEP">WEP</option><option value="nopass">No password</option></select></label></div>`,
 email:`<div class="field"><label>Email address<input id="email" type="email" placeholder="name@example.com"></label></div><div class="field"><label>Subject<input id="subject"></label></div><div class="field"><label>Message<textarea id="emailMessage"></textarea></label></div>`,
 phone:`<div class="field"><label>Phone number<input id="phone" type="tel" placeholder="+93700000000"></label></div>`,
 contact:`<div class="field"><label>Full name<input id="fullName"></label></div><div class="field"><label>Phone<input id="contactPhone" type="tel"></label></div><div class="field"><label>Email<input id="contactEmail" type="email"></label></div><div class="field"><label>Organization<input id="organization"></label></div>`,
 location:`<div class="field"><label>Latitude<input id="latitude" type="number" step="any" placeholder="34.5553"></label></div><div class="field"><label>Longitude<input id="longitude" type="number" step="any" placeholder="69.2075"></label></div>`,
 sms:`<div class="field"><label>Phone number<input id="smsPhone" type="tel"></label></div><div class="field"><label>Message<textarea id="smsMessage"></textarea></label></div>`,
 event:`<div class="field"><label>Event title<input id="eventTitle"></label></div><div class="field"><label>Start<input id="eventStart" type="datetime-local"></label></div><div class="field"><label>End<input id="eventEnd" type="datetime-local"></label></div><div class="field"><label>Location<input id="eventLocation"></label></div><div class="field"><label>Description<textarea id="eventDescription"></textarea></label></div>`,
 social:`<div class="field"><label>Social/profile URL<input id="socialUrl" type="url" placeholder="https://instagram.com/username"></label></div>`,
 whatsapp:`<div class="field"><label>WhatsApp number<input id="waPhone" type="tel" placeholder="+93700000000"></label></div><div class="field"><label>Message<textarea id="waMessage"></textarea></label></div>`,
 app:`<div class="field"><label>App / download URL<input id="appUrl" type="url" placeholder="https://example.com/app"></label></div>`
 };
 $('#fields').innerHTML=m[S.type];$('#formMessage').textContent='';readout();updateQuality();
}
const qesc=x=>String(x).replace(/([\\;,:"])/g,'\\$1');
function payload(){switch(S.type){
 case'url':case'social':case'app':{let id=S.type==='url'?'url':S.type==='social'?'socialUrl':'appUrl',x=v(id);if(!x)throw Error('Please enter a URL.');let u;try{u=new URL(x)}catch{throw Error('Enter a valid URL.')}if(!/^https?:$/.test(u.protocol))throw Error('Use http:// or https://.');return u.href}
 case'text':{let x=v('text');if(!x)throw Error('Please enter some text.');return x}
 case'wifi':{let s=v('ssid'),p=v('password'),t=$('#security').value;if(!s)throw Error('Wi-Fi network name is required.');if(t!=='nopass'&&!p)throw Error('Wi-Fi password is required.');return `WIFI:T:${t};S:${qesc(s)};P:${qesc(p)};;`}
 case'email':{let e=v('email');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e))throw Error('Enter a valid email.');return `mailto:${e}?subject=${encodeURIComponent(v('subject'))}&body=${encodeURIComponent(v('emailMessage'))}`}
 case'phone':{let x=v('phone');if(!x)throw Error('Phone number is required.');return `tel:${x}`}
 case'contact':{let n=v('fullName'),e=v('contactEmail');if(!n)throw Error('Full name is required.');if(e&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e))throw Error('Enter a valid contact email.');let parts=n.split(/\s+/),fam=parts.length>1?parts.pop():'',L=['BEGIN:VCARD','VERSION:3.0','N:'+vesc(fam)+';'+vesc(parts.join(' '))+';;;','FN:'+vesc(n)];if(v('contactPhone'))L.push('TEL:'+vesc(v('contactPhone')));if(e)L.push('EMAIL:'+vesc(e));if(v('organization'))L.push('ORG:'+vesc(v('organization')));L.push('END:VCARD');return L.join('\n')}
 case'location':{let a=Number(v('latitude')),b=Number(v('longitude'));if(!Number.isFinite(a)||a<-90||a>90||!Number.isFinite(b)||b<-180||b>180)throw Error('Enter valid latitude and longitude.');return `geo:${a},${b}`}
 case'sms':{let p=v('smsPhone');if(!p)throw Error('Phone number is required.');return `SMSTO:${p}:${v('smsMessage')}`}
 case'event':{let t=v('eventTitle'),s=v('eventStart'),en=v('eventEnd');if(!t||!s)throw Error('Event title and start time are required.');if(en&&new Date(en)<=new Date(s))throw Error('End time must be after the start time.');let f=x=>new Date(x).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z');let L=['BEGIN:VCALENDAR','VERSION:2.0','BEGIN:VEVENT','SUMMARY:'+vesc(t),'DTSTART:'+f(s)];if(en)L.push('DTEND:'+f(en));if(v('eventLocation'))L.push('LOCATION:'+vesc(v('eventLocation')));if(v('eventDescription'))L.push('DESCRIPTION:'+vesc(v('eventDescription')));L.push('END:VEVENT','END:VCALENDAR');return L.join('\n')}
 case'whatsapp':{let p=v('waPhone').replace(/[^\d]/g,'');if(!p)throw Error('WhatsApp number is required.');return `https://wa.me/${p}${v('waMessage')?'?text='+encodeURIComponent(v('waMessage')):''}`}
 }}
function luminance(hex){let z=hex.replace('#','').match(/../g).map(x=>parseInt(x,16)/255).map(x=>x<=.03928?x/12.92:((x+.055)/1.055)**2.4);return .2126*z[0]+.7152*z[1]+.0722*z[2]}
function contrast(a,b){let x=luminance(a),y=luminance(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05)}
function colorCheck(){let bg=$('#bgColor').value,cols=[$('#qrColor').value];if($('#gradientMode').value!=='none')cols.push($('#qrColor2').value);let c=Math.min(...cols.map(x=>contrast(x,bg))),inv=cols.some(x=>luminance(x)>luminance(bg)),msg=inv?'Light QR on a darker background (inverted). Many scanners cannot read this. Use a dark QR on a light background.':c<4.5?`Contrast ${c.toFixed(2)}:1 is below the recommended 4.5:1 for strong reliability.`:'';return{c,inv,msg}}
function matrix(data,ec='H'){if(typeof qrcode!=='function')throw Error('Local QR engine unavailable.');let q=qrcode(0,ec);q.addData(data);q.make();return q}
function gradientDef(total){let mode=$('#gradientMode').value;if(mode==='none')return {fill:$('#qrColor').value,def:''};let a=$('#qrColor').value,b=$('#qrColor2').value,deg=mode==='horizontal'?0:mode==='vertical'?90:Number($('#gradientAngle').value),rad=deg*Math.PI/180,c=total/2,r=c*(Math.abs(Math.cos(rad))+Math.abs(Math.sin(rad))),dx=Math.cos(rad)*r,dy=Math.sin(rad)*r,def=`<defs><linearGradient id="qrGrad" gradientUnits="userSpaceOnUse" x1="${(c-dx).toFixed(2)}" y1="${(c-dy).toFixed(2)}" x2="${(c+dx).toFixed(2)}" y2="${(c+dy).toFixed(2)}"><stop offset="0%" stop-color="${a}"/><stop offset="100%" stop-color="${b}"/></linearGradient></defs>`;return{fill:'url(#qrGrad)',def}}
function svgFor(q,size,opts={}){
 const n=q.getModuleCount(),quiet=Number(opts.quiet||4),cell=Math.max(2,Math.floor(size/(n+quiet*2))),total=(n+quiet*2)*cell,fill=opts.fill||opts.fg||'#111827',bg=opts.bg||'#fff';
 let g=opts.grad?opts.grad(total):null,s=g?g.def:(opts.def||'');s+=`<rect width="${total}" height="${total}" fill="${bg}"/>`;
 for(let r=0;r<n;r++)for(let c=0;c<n;c++)if(q.isDark(r,c)){let x=(c+quiet)*cell,y=(r+quiet)*cell,rx=opts.dot==='round'?cell*.42:0;s+=`<rect x="${x}" y="${y}" width="${cell+.1}" height="${cell+.1}"${rx?` rx="${rx}"`:''} fill="${g?g.fill:fill}"/>`}
 return {body:s,width:total,height:total,cell,n};
}
function frameSvg(inner,w,h){let fs=$('#frameStyle').value;if(fs==='none')return {svg:inner,w,h};let text=fs==='scan'?'SCAN ME':v('frameText')||'SCAN ME',pos=$('#framePosition').value,fc=$('#frameColor').value,tc=$('#frameTextColor').value,pad=24,bar=58,totalH=h+bar,top=pos==='top';let y=top?0:h;let svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${totalH}" viewBox="0 0 ${w} ${totalH}"><rect width="${w}" height="${totalH}" fill="${$('#bgColor').value}"/>`;if(top)svg+=`<g transform="translate(0 ${bar})">${inner}</g>`;else svg+=inner;let ty=top?38:h+38,rx=fs==='pill'?18:0;svg+=`<rect x="${pad}" y="${ty-27}" width="${w-pad*2}" height="40" rx="${rx}" fill="${fc}"/><text x="${w/2}" y="${ty}" text-anchor="middle" font-family="Arial, sans-serif" font-size="18" font-weight="700" fill="${tc}">${esc(text)}</text></svg>`;return{svg,w,h:totalH}}
function buildSvg(){let size=Number($('#qrSize').value),q=matrix(S.payload,ecl()),raw=svgFor(q,size,{quiet:$('#quietZone').value,fill:$('#qrColor').value,bg:$('#bgColor').value,dot:$('#dotStyle').value,grad:gradientDef}),_s=(S.cell=raw.cell,S.mods=raw.n),inner=`<svg xmlns="http://www.w3.org/2000/svg" width="${raw.width}" height="${raw.height}" viewBox="0 0 ${raw.width} ${raw.height}">${raw.body}</svg>`;
 if(S.logo){let pct=Number($('#logoSize').value)/100,z=raw.width*pct,x=(raw.width-z)/2,op=Number($('#logoOpacity').value)/100;inner=inner.replace('</svg>',`<rect x="${x-6}" y="${x-6}" width="${z+12}" height="${z+12}" rx="12" fill="${$('#bgColor').value}"/><image href="${S.logo}" x="${x}" y="${x}" width="${z}" height="${z}" opacity="${op}" preserveAspectRatio="xMidYMid meet"/></svg>`)}
 return frameSvg(inner,raw.width,raw.height).svg;
}
function generate(save=true){try{S.payload=payload();$('#formMessage').textContent='';let k=colorCheck();$('#contrastWarning').classList.toggle('hidden',!k.msg);$('#contrastWarning').textContent=k.msg;S.svg=buildSvg();$('#qrOutput').innerHTML=S.svg;$('#qrOutput').classList.remove('hidden');$('#qrEmpty').classList.add('hidden');$('#actions').classList.remove('hidden');$('#qrStatus').textContent=k.msg?'Generated \u2014 check colors':'Generated';readout();updateQuality();if(save)saveHistory()}catch(e){$('#formMessage').textContent=friendly(e);$('#qrStatus').textContent='Ready'}}
function readout(){$('#readoutType').textContent=typeLabels[S.type]||S.type.toUpperCase();$('#readoutSize').textContent=$('#qrSize').selectedOptions[0].text;$('#readoutEC').textContent=ecl()+' EC';if($('#ecScore'))$('#ecScore').textContent=ecl()}
function updateQuality(){let score='—',c='—';if($('#qrColor')&&$('#bgColor')){let k=colorCheck(),n=k.c;c=n.toFixed(2)+':1';score=k.inv?'Inverted':n>=7?'Excellent':n>=4.5?'Good':'Low';$('#qualityScore').textContent=score;$('#contrastScore').textContent=c;$('#readoutQuality').textContent=score}}
function hist(){try{return JSON.parse(localStorage.getItem(H)||'[]')}catch{return[]}}
function saveHistory(){let a=hist();let existing=a.find(x=>x.type===S.type&&x.data===S.payload);let item=existing||{id:crypto.randomUUID?.()||String(Date.now()+Math.random()),type:S.type,data:S.payload,date:new Date().toISOString(),favorite:false};item.date=new Date().toISOString();a=[item,...a.filter(x=>x.id!==item.id)].slice(0,MAX);localStorage.setItem(H,JSON.stringify(a));renderHistory();refreshFilter()}
const shown=x=>{if(x.type!=='wifi')return x.data;let m=x.data.match(/^(WIFI:T:[^;]*;S:(?:\\.|[^;\\])*;P:)(?:\\.|[^;\\])*(;;)$/);return m?m[1]+'\u2022\u2022\u2022\u2022\u2022\u2022'+m[2]:x.data};
function renderHistory(){let list=hist(),q=($('#historySearch')?.value||'').toLowerCase(),f=$('#historyFilter')?.value||'all',sort=$('#historySort')?.value||'new';let a=list.filter(x=>(f==='all'||x.type===f)&&(!q||shown(x).toLowerCase().includes(q)));if(sort==='old')a.sort((x,y)=>new Date(x.date)-new Date(y.date));if(sort==='favorite')a.sort((x,y)=>Number(y.favorite)-Number(x.favorite)||new Date(y.date)-new Date(x.date));$('#historyList').innerHTML=a.length?a.map(x=>`<article class="history-item"><div class="history-icon">QR</div><div class="history-main"><div class="history-type">${x.favorite?'★ ':''}${esc(typeLabels[x.type]||x.type)}</div><div class="history-data">${esc(shown(x))}</div><div class="history-date">${new Date(x.date).toLocaleString()}</div></div><div class="history-actions"><button class="favorite-btn" title="Favorite" data-fav="${esc(x.id)}">${x.favorite?'★':'☆'}</button><button data-use="${esc(x.id)}">Edit</button><button data-dup="${esc(x.id)}">Duplicate</button><button data-del="${esc(x.id)}">Delete</button></div></article>`).join(''):'<div class="card" style="text-align:center;color:var(--muted)">No QR codes saved yet.</div>'}
function refreshFilter(){let cur=$('#historyFilter').value,types=[...new Set(hist().map(x=>x.type))];$('#historyFilter').innerHTML='<option value="all">All types</option>'+types.map(x=>`<option value="${esc(x)}">${esc(typeLabels[x]||x)}</option>`).join('');if(types.includes(cur))$('#historyFilter').value=cur}
function restore(x){S.type=x.type;$$('.type').forEach(b=>b.classList.toggle('active',b.dataset.type===S.type));renderFields();let set=(id,z)=>{if($('#'+id))$('#'+id).value=z};if(S.type==='url')set('url',x.data);if(S.type==='social')set('socialUrl',x.data);if(S.type==='app')set('appUrl',x.data);if(S.type==='text')set('text',x.data);if(S.type==='phone')set('phone',x.data.replace(/^tel:/,''));if(S.type==='whatsapp'){try{let u=new URL(x.data);set('waPhone',u.pathname.replace(/\D/g,''));set('waMessage',u.searchParams.get('text')||'')}catch{}}if(S.type==='location'){let m=x.data.match(/^geo:([^,]+),(.+)$/);if(m){set('latitude',m[1]);set('longitude',m[2])}}if(S.type==='sms'){let m=x.data.match(/^SMSTO:([^:]*):(.*)$/s);if(m){set('smsPhone',m[1]);set('smsMessage',m[2])}}if(S.type==='email'){try{let u=new URL(x.data);set('email',u.pathname);set('subject',u.searchParams.get('subject')||'');set('emailMessage',u.searchParams.get('body')||'')}catch{}}if(S.type==='wifi'){let m=x.data.match(/^WIFI:T:([^;]*);S:((?:\\.|[^;\\])*);P:((?:\\.|[^;\\])*);;$/s);if(m){set('security',m[1]);set('ssid',m[2].replace(/\\(.)/g,'$1'));set('password',m[3].replace(/\\(.)/g,'$1'))}}
 if(S.type==='contact'){for(const ln of x.data.split('\n')){let m=ln.match(/^(FN|TEL|EMAIL|ORG):(.*)$/);if(!m)continue;set({FN:'fullName',TEL:'contactPhone',EMAIL:'contactEmail',ORG:'organization'}[m[1]],vunesc(m[2]))}}
 if(S.type==='event'){let loc=z=>{let m=z.match(/^(\d{4})(\d\d)(\d\d)T(\d\d)(\d\d)(\d\d)Z$/);if(!m)return'';let d=new Date(Date.UTC(+m[1],m[2]-1,+m[3],+m[4],+m[5],+m[6])),p=n=>String(n).padStart(2,'0');return`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`};for(const ln of x.data.split('\n')){let m=ln.match(/^(SUMMARY|DTSTART|DTEND|LOCATION|DESCRIPTION):(.*)$/);if(!m)continue;let k=m[1];set({SUMMARY:'eventTitle',DTSTART:'eventStart',DTEND:'eventEnd',LOCATION:'eventLocation',DESCRIPTION:'eventDescription'}[k],k==='DTSTART'||k==='DTEND'?loc(m[2]):vunesc(m[2]))}}
 switchPage('generator');generate(false)}
function blob(b,n){let a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1200)}
async function canvas(){let svg=$('#qrOutput svg');if(!svg)throw Error('Generate a QR first.');let xml=new XMLSerializer().serializeToString(svg),u=URL.createObjectURL(new Blob([xml],{type:'image/svg+xml'})),i=new Image();await new Promise((r,j)=>{i.onload=r;i.onerror=j;i.src=u});let c=document.createElement('canvas'),s=Math.max(1,Number($('#qrSize').value));let ratio=i.width&&i.height?i.width/i.height:1;c.width=Math.round(Math.max(s,i.width*Math.ceil(6/(S.cell||2))));c.height=Math.round(c.width/ratio);{let cx=c.getContext('2d');cx.drawImage(i,0,0,c.width,c.height)}URL.revokeObjectURL(u);return c}
async function exportRaster(type,ext){try{let c=await canvas(),big=c.width>Number($('#qrSize').value);c.toBlob(b=>{blob(b,`qr-studio.${ext}`);if(big)$('#qrStatus').textContent='Exported larger so it stays readable'},type,.94)}catch(e){$('#formMessage').textContent=ext.toUpperCase()+' export failed: '+e.message}}
async function png(){return exportRaster('image/png','png')}
async function jpg(){return exportRaster('image/jpeg','jpg')}
async function webp(){return exportRaster('image/webp','webp')}
function svg(){if(S.svg)blob(new Blob([S.svg],{type:'image/svg+xml'}),'qr-studio.svg')}
async function copyQR(){try{let c=await canvas(),b=await new Promise(r=>c.toBlob(r,'image/png'));if(navigator.clipboard?.write&&window.ClipboardItem)await navigator.clipboard.write([new ClipboardItem({'image/png':b})]);else await navigator.clipboard.writeText(S.payload);$('#qrStatus').textContent='Copied'}catch{try{await navigator.clipboard.writeText(S.payload);$('#qrStatus').textContent='Text copied'}catch{$('#formMessage').textContent='Clipboard is unavailable.'}}}
function printQR(){if(!S.svg)return;let w=open('','_blank','width=650,height=750');if(!w)return;w.document.write(`<title>QR Studio Print</title><style>body{margin:0;display:grid;place-items:center;min-height:100vh}svg{width:80vw;max-width:560px;height:auto}</style>${S.svg}`);w.document.close();setTimeout(()=>{w.print();w.close()},250)}
function inspectQR(){if(!S.payload)return openModal('QR Inspector','<p>Generate a QR code first.</p>');let k=colorCheck(),c=k.c,size=Number($('#qrSize').value),quiet=Number($('#quietZone').value),logo=S.logo?Number($('#logoSize').value):0,mods=S.mods||0,e=ecl();let rows=[['Contrast',k.inv?'Inverted (light on dark)':c>=7?'Excellent':c>=4.5?'Good':'Low',!k.inv&&c>=4.5],['Output size',size+' px',size>=300],['Quiet zone',quiet+' modules',quiet>=4],['Error correction',e,e!=='L'],['Density',mods+' \u00d7 '+mods+' modules',mods<=97],['Logo safety',logo?logo+'% of QR width':'No logo',!logo||logo<=22]];openModal('QR Inspector',`<div class="inspector">${rows.map(r=>`<div class="inspector-row"><span>${esc(r[0])}</span><strong class="${r[2]?'inspector-good':'inspector-warn'}">${esc(r[1])}</strong></div>`).join('')}<p class="muted">This is a design/readability aid, not a guarantee across every camera, print process or surface.</p></div>`)}
let jsQRLoad=null;
function loadJsQR(){if(typeof window.jsQR==='function')return Promise.resolve(true);if(jsQRLoad)return jsQRLoad;jsQRLoad=new Promise(res=>{let s=document.createElement('script');s.src='vendor/jsQR.js';s.onload=()=>res(typeof window.jsQR==='function');s.onerror=()=>{jsQRLoad=null;res(false)};document.head.appendChild(s)});return jsQRLoad}
async function nativeOK(){try{if(!('BarcodeDetector'in window))return false;if(BarcodeDetector.getSupportedFormats){let f=await BarcodeDetector.getSupportedFormats();return f.includes('qr_code')}return true}catch{return false}}
async function getEngine(){if(await nativeOK()){let d=new BarcodeDetector({formats:['qr_code']});return{detect:async src=>{let c=await d.detect(src);return c&&c[0]&&c[0].rawValue||''}}}if(await loadJsQR()){let cv=document.createElement('canvas'),cx=cv.getContext('2d',{willReadFrequently:true});return{detect:async src=>{let w=src.videoWidth||src.width,h=src.videoHeight||src.height;if(!w||!h)return'';let sc=Math.min(1,900/Math.max(w,h));cv.width=Math.round(w*sc);cv.height=Math.round(h*sc);cx.drawImage(src,0,0,cv.width,cv.height);let id=cx.getImageData(0,0,cv.width,cv.height),r=window.jsQR(id.data,id.width,id.height,{inversionAttempts:'attemptBoth'});return r&&r.data||''}}}return null}
const noEngine='QR scanning is not available in this browser, and the offline scanner library (vendor/jsQR.js) is not installed.';
async function startScanner(){const m=$('#scannerMessage');m.textContent='';if(S.running)return;const eng=await getEngine();if(!eng){m.textContent=noEngine;return}try{const reader=$('#reader');reader.innerHTML='<video id="scannerVideo" playsinline muted></video><div class="scan-guide">Place the QR inside the frame</div>';const video=$('#scannerVideo');const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});video.srcObject=stream;await video.play();S.scanner={stream,video,raf:0,last:0};S.running=true;$('#startScanner').disabled=true;$('#stopScanner').disabled=false;let busy=false;const loop=async ts=>{if(!S.running||!S.scanner)return;if(!busy&&ts-S.scanner.last>150&&video.readyState>=2){S.scanner.last=ts;busy=true;try{const val=await eng.detect(video);if(val&&S.running){busy=false;onScan(val);return}}catch{}busy=false}if(!S.running||!S.scanner)return;S.scanner.raf=requestAnimationFrame(loop)};S.scanner.raf=requestAnimationFrame(loop)}catch(e){$('#scannerMessage').textContent='Camera could not start. Allow camera permission and use HTTPS or localhost.';await stopScanner()}}
async function stopScanner(){if(S.scanner){try{cancelAnimationFrame(S.scanner.raf)}catch{}try{S.scanner.stream?.getTracks().forEach(t=>t.stop())}catch{}}S.scanner=null;S.running=false;if($('#reader'))$('#reader').innerHTML='<span>Camera scanner is ready.</span>';if($('#startScanner'))$('#startScanner').disabled=false;if($('#stopScanner'))$('#stopScanner').disabled=true}
function onScan(x){stopScanner();$('#scanText').textContent=x;$('#scanResult').classList.remove('hidden');let ok=/^https?:\/\//i.test(x);$('#openScan').classList.toggle('hidden',!ok);$('#openScan').onclick=()=>window.open(new URL(x).href,'_blank','noopener,noreferrer')}
async function scanImage(f){if(!f)return;const m=$('#scannerMessage');m.textContent='';const eng=await getEngine();if(!eng){m.textContent=noEngine;$('#scanImage').value='';return}try{const bmp=await createImageBitmap(f);let val='';try{val=await eng.detect(bmp)}finally{bmp.close?.()}if(val)onScan(val);else m.textContent='No readable QR code found in that image.'}catch{m.textContent='No readable QR code found in that image.'}$('#scanImage').value=''}
function switchPage(p){if(p!=='scanner')stopScanner();$$('.page').forEach(x=>x.classList.remove('active'));$('#page-'+p).classList.add('active');$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===p));history.replaceState(null,'','#'+p);scrollTo(0,0)}
function theme(){let d=document.body.classList.toggle('dark');localStorage.setItem(T,d?'dark':'light');$('#themeToggle').textContent=d?'☀':'☾'}
function templatesUI(){$('#templateGrid').innerHTML=templates.map((x,i)=>`<article class="template"><div class="history-icon">${i+1}</div><h3>${esc(x[0])}</h3><p>${esc(x[2])}</p><button class="primary" data-template="${i}">Use template</button></article>`).join('')}
function useTemplate(i){let x=templates[i];S.type=x[1];$$('.type').forEach(b=>b.classList.toggle('active',b.dataset.type===S.type));renderFields();let id={url:'url',wifi:'ssid',contact:'fullName',email:'email',phone:'phone',sms:'smsPhone',event:'eventTitle',social:'socialUrl',whatsapp:'waPhone',app:'appUrl'}[S.type];if(id)$('#'+id).value=x[3];switchPage('generator')}
function makeBatchSvg(value,fg,bg){let q=matrix(value,'H');let r=svgFor(q,260,{quiet:4,fill:fg,bg,dot:'square'});return `<svg xmlns="http://www.w3.org/2000/svg" width="${r.width}" height="${r.height}" viewBox="0 0 ${r.width} ${r.height}">${r.body}</svg>`}
async function batch(){let limit=Number($('#batchLimit').value),all=$('#batchInput').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),lines=all.slice(0,limit);$('#batchMessage').textContent=all.length>limit?'Only the first '+limit+' of '+all.length+' values were used.':'';if(!lines.length){$('#batchMessage').textContent='Add at least one value.';return}S.batch=[];S.cancelBatch=false;$('#generateBatch').disabled=true;$('#batchProgress').style.width='0%';$('#cancelBatch').disabled=false;$('#downloadBatch').disabled=true;let box=$('#batchPreview');box.innerHTML='';for(let i=0;i<lines.length;i++){if(S.cancelBatch)break;try{let s=makeBatchSvg(lines[i],$('#batchColor').value,$('#batchBg').value);S.batch.push({svg:s,name:`qr-${String(i+1).padStart(3,'0')}.svg`});let d=document.createElement('div');d.className='batch-item';d.innerHTML=s+'<small>'+esc(lines[i])+'</small>';box.appendChild(d)}catch(e){$('#batchMessage').textContent=`Stopped at item ${i+1}: ${friendly(e)}`;break}let pct=Math.round(((i+1)/lines.length)*100);$('#batchProgress').style.width=pct+'%';$('#batchProgressText').textContent=`${i+1} / ${lines.length} generated`;if(i%5===0)await new Promise(r=>setTimeout(r,0))}$('#batchCount').textContent=S.batch.length+' QR code'+(S.batch.length===1?'':'s');$('#downloadBatch').disabled=!S.batch.length;$('#cancelBatch').disabled=true;$('#generateBatch').disabled=false;if(S.cancelBatch)$('#batchProgressText').textContent='Cancelled';}
function csvRows(t){let rows=[],row=[],cur='',q=false;for(let i=0;i<t.length;i++){let ch=t[i];if(q){if(ch==='"'){if(t[i+1]==='"'){cur+='"';i++}else q=false}else cur+=ch}else if(ch==='"')q=true;else if(ch===','){row.push(cur);cur=''}else if(ch==='\n'||ch==='\r'){if(ch==='\r'&&t[i+1]==='\n')i++;row.push(cur);rows.push(row);row=[];cur=''}else cur+=ch}row.push(cur);rows.push(row);return rows}
function parseBatchFile(t,csv){t=t.replace(/^\uFEFF/,'');if(!csv)return t.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);let vals=csvRows(t).map(r=>(r[0]||'').replace(/\s*\n\s*/g,' ').trim()).filter(Boolean);if(vals.length>1&&/^(url|link|text|value|data|content)$/i.test(vals[0]))vals.shift();return vals}
function zip(files){let enc=new TextEncoder();files=files.map(f=>[enc.encode(f.name),enc.encode(f.svg)]);function u16(n){return new Uint8Array([n&255,n>>8])}function u32(n){return new Uint8Array([n&255,n>>8,n>>16,n>>24])}function crc(a){let c=~0;for(let b of a){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return~c>>>0}let parts=[],cent=[],off=0;for(let [n,d]of files){let c=crc(d),h=new Uint8Array([...u32(0x04034b50),...u16(20),...u16(0),...u16(0),...u16(0),...u16(0),...u32(c),...u32(d.length),...u32(d.length),...u16(n.length),...u16(0)]);parts.push(new Blob([h,n,d]));cent.push([n,d,c,off]);off+=h.length+n.length+d.length}let cs=0,cp=cent.map(([n,d,c,o])=>{let h=new Uint8Array([...u32(0x02014b50),...u16(20),...u16(20),...u16(0),...u16(0),...u16(0),...u16(0),...u32(c),...u32(d.length),...u32(d.length),...u16(n.length),...u16(0),...u16(0),...u16(0),...u16(0),...u32(0),...u32(o)]);cs+=h.length+n.length;return new Blob([h,n])});return new Blob([...parts,...cp,new Uint8Array([...u32(0x06054b50),...u16(0),...u16(0),...u16(files.length),...u16(files.length),...u32(cs),...u32(off),...u16(0)])],{type:'application/zip'})}
function downloadBatch(){if(S.batch.length)blob(zip(S.batch),'qr-studio-batch.zip')}
function openModal(title,body){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modal').classList.remove('hidden')}
function closeModal(){$('#modal').classList.add('hidden')}
function moreAction(a){$('#moreMenu').hidden=true;$('#moreBtn').setAttribute('aria-expanded','false');if(a==='shortcuts')openModal('Keyboard shortcuts',`<div class="modal-list"><div><b>G</b> — focus Generator</div><div><b>S</b> — open Scanner</div><div><b>B</b> — open Batch</div><div><b>Esc</b> — close menus</div></div>`);if(a==='privacy')openModal('Privacy center','<p>QR Studio v1 generates and stores QR data in your browser. There is no QR account, application database, or built-in analytics. Camera scanning requires browser permission and may depend on your browser security context.</p>');if(a==='about')openModal('About QR Studio v1','<p>A client-side QR toolkit with generator, designer, scanner, batch creation, templates, local history, export and PWA support.</p>');if(a==='reset'){if(confirm('Reset generator settings and content?')){S.logo=null;location.hash='#generator';location.reload()}}if(a==='install'&&window._pwa){window._pwa.prompt();window._pwa.userChoice.then(()=>{window._pwa=null;$('#menuInstall').hidden=true})}}
function init(){
 if(localStorage.getItem(T)==='dark'){document.body.classList.add('dark');$('#themeToggle').textContent='☀'}
 renderFields();templatesUI();renderHistory();refreshFilter();
 $$('.type').forEach(b=>b.onclick=()=>{S.type=b.dataset.type;$$('.type').forEach(x=>x.classList.toggle('active',x===b));renderFields()});
 $$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.panel).classList.add('active')});
 $$('nav button,[data-page]').forEach(b=>b.onclick=e=>{e.preventDefault();switchPage(b.dataset.page)});
 $('#themeToggle').onclick=theme;$('#moreBtn').onclick=()=>{$('#moreMenu').hidden=!$('#moreMenu').hidden;$('#moreBtn').setAttribute('aria-expanded',String(!$('#moreMenu').hidden))};$$('[data-more]').forEach(b=>b.onclick=()=>moreAction(b.dataset.more));$('#modalClose').onclick=closeModal;$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal()};
 $('#generateBtn').onclick=()=>generate();$('#clearHistory').onclick=()=>{if(confirm('Clear local QR history?')){localStorage.removeItem(H);renderHistory();refreshFilter()}};$('#historySearch').oninput=renderHistory;$('#historyFilter').onchange=renderHistory;$('#historySort').onchange=renderHistory;$('#historyList').onclick=e=>{let b=e.target.closest('button');if(!b)return;let a=hist(),x=a.find(y=>y.id===b.dataset.use||y.id===b.dataset.fav||y.id===b.dataset.dup||y.id===b.dataset.del);if(!x)return;if(b.dataset.use){restore(x)}else if(b.dataset.fav){x.favorite=!x.favorite;localStorage.setItem(H,JSON.stringify(a));renderHistory()}else if(b.dataset.dup){a.unshift({...x,id:crypto.randomUUID?.()||String(Date.now()+Math.random()),date:new Date().toISOString(),favorite:false});localStorage.setItem(H,JSON.stringify(a.slice(0,MAX)));renderHistory();refreshFilter()}else if(b.dataset.del){if(confirm('Delete this QR from your local library?')){localStorage.setItem(H,JSON.stringify(a.filter(y=>y.id!==x.id)));renderHistory();refreshFilter()}}};
 $$('[data-action]').forEach(b=>b.onclick=()=>({png,svg,jpg,webp,copy:copyQR,print:printQR}[b.dataset.action])());$('#inspectBtn').onclick=inspectQR;
 $('#startScanner').onclick=startScanner;$('#stopScanner').onclick=stopScanner;$('#scanImage').onchange=e=>scanImage(e.target.files[0]);$('#copyScan').onclick=async()=>{try{await navigator.clipboard.writeText($('#scanText').textContent);$('#scannerMessage').textContent='Result copied.'}catch{$('#scannerMessage').textContent='Clipboard unavailable.'}};
 $('#logoInput').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{S.logo=r.result;$('#logoName').textContent=f.name;if(S.payload)generate(false)};r.readAsDataURL(f)};$('#removeLogo').onclick=()=>{S.logo=null;$('#logoInput').value='';$('#logoName').textContent='No logo selected';if(S.payload)generate(false)};
 ['qrSize','ecLevel','qrColor','bgColor','dotStyle','quietZone','gradientMode','qrColor2','gradientAngle','frameStyle','frameText','framePosition','frameColor','frameTextColor','logoSize','logoOpacity'].forEach(id=>{let el=$('#'+id);if(!el)return;el.oninput=el.onchange=()=>{if(id==='frameStyle')$('#frameTextWrap').classList.toggle('hidden',el.value==='none');if(id==='gradientMode'){$('#gradientColors').classList.toggle('hidden',el.value==='none');$('#gradientAngle').closest('label').classList.toggle('hidden',el.value!=='diagonal')}readout();updateQuality();if(S.payload)generate(false)}});
 $('#generateBatch').onclick=batch;$('#cancelBatch').onclick=()=>S.cancelBatch=true;$('#downloadBatch').onclick=downloadBatch;$('#batchFile').onchange=e=>{let f=e.target.files[0];if(!f)return;let csv=/\.csv$/i.test(f.name),r=new FileReader();r.onload=()=>{let vals=parseBatchFile(String(r.result),csv);$('#batchInput').value=vals.join('\n');$('#batchProgressText').textContent='Imported '+vals.length+' value'+(vals.length===1?'':'s')+(csv?' (first column)':'');e.target.value=''};r.readAsText(f)};
 $('#templateGrid').onclick=e=>{let b=e.target.closest('[data-template]');if(b)useTemplate(+b.dataset.template)};
 window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();window._pwa=e;$('#menuInstall').hidden=false});
 if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();$('#moreMenu').hidden=true}if(e.target.matches('input,textarea,select'))return;let k=e.key.toLowerCase();if(k==='g')switchPage('generator');if(k==='s')switchPage('scanner');if(k==='b')switchPage('batch')});
 let p=location.hash.slice(1);if(['generator','scanner','batch','templates','history'].includes(p))switchPage(p);window.addEventListener('beforeunload',stopScanner)
}
document.addEventListener('DOMContentLoaded',init)
})();
